`ifndef DEFINE_STATE

// This defines the states
typedef enum logic [1:0] {
	S_IDLE,
	S_ENABLE_UART_RX,
	S_WAIT_UART_RX
} top_state_type;

typedef enum logic [1:0] {
	S_RXC_IDLE,
	S_RXC_SYNC,
	S_RXC_ASSEMBLE_DATA,
	S_RXC_STOP_BIT
} RX_Controller_state_type;

typedef enum logic [2:0] {
	S_US_IDLE,
	S_US_STRIP_FILE_HEADER_1,
	S_US_STRIP_FILE_HEADER_2,
	S_US_START_FIRST_BYTE_RECEIVE,
	S_US_WRITE_FIRST_BYTE,
	S_US_START_SECOND_BYTE_RECEIVE,
	S_US_WRITE_SECOND_BYTE
} UART_SRAM_state_type;

typedef enum logic [3:0] {
	S_VS_WAIT_NEW_PIXEL_ROW,
	S_VS_NEW_PIXEL_ROW_DELAY_1,
	S_VS_NEW_PIXEL_ROW_DELAY_2,
	S_VS_NEW_PIXEL_ROW_DELAY_3,
	S_VS_NEW_PIXEL_ROW_DELAY_4,
	S_VS_NEW_PIXEL_ROW_DELAY_5,
	S_VS_FETCH_PIXEL_DATA_0,
	S_VS_FETCH_PIXEL_DATA_1,
	S_VS_FETCH_PIXEL_DATA_2,
	S_VS_FETCH_PIXEL_DATA_3
} VGA_SRAM_state_type;

typedef enum logic [4:0] {
	S_M1_LEAD_1,
	S_M1_LEAD_2,
	S_M1_LEAD_3,
	S_M1_LEAD_4,
	S_M1_LEAD_5,
	S_M1_LEAD_6,
	S_M1_LEAD_7,
	S_M1_LEAD_8,
	S_M1_LEAD_9,
	S_M1_LEAD_10,
	S_M1_CC_1,
	S_M1_CC_2,
	S_M1_CC_3,
	S_M1_CC_4,
	S_M1_CC_5,
	S_M1_UP_1,
	S_M1_UP_2,
	S_M1_UP_3,
	S_M1_UP_4,
	S_M1_UP_5,
	S_M1_UP_6,
	S_M1_UP_7
} MILESTONE1_state_type;
`define DEFINE_STATE 1
`endif
